### PR TITLE
Getting 4.1 ready

### LINKED ISSUE #4: Add filters for sorting to the "Your URLs" page
Is there any way to put a filter on the "Your URLs" in go.unl.edu so I can see my most recent URLs from the top and not have to scroll down? I would like to be able to filter by date made or maybe even by alpha. A possibility?

-- From Shari in housing

### LINKED ISSUE #5: Management Interface Issues
via @snrwebmaster

There are a number of issues I love to see fixed, modified or changed on the go.un.edu application.

Your URLS
The design of the results are not easily scanable. You need to review each band. The old table design where information is in columns is much more usable.

The order of them is not helpful. Alphabetical is my preference or at least the most first. Right now I have been told that it is by date submitted but it does not seem to be working that way.

If your go to Your URLS do anything such as delete or want to add new one you have to use the browser back button. There are no breadcrumbs to help with navigation

Log In
When you log in The log in area does not acknowledge that you have logged in

### LINKED ISSUE #7: White on white!, confirmation box input text is unreadable
The confirmation screen displays the goURL within an input, but the text is unreadable.

screen shot 2015-12-04 at 3 49 19 pm

### LINKED ISSUE #8: URLs improperly validated for unl.edu domain
The following URL can be shortened without authentication:
http://cashmere.unl.edu.unl.es/hacker/phishing/login.php

### PR DESCRIPTION
**Pull request by kabel**
* Switch to composer for deps
* Switch to php7 safe mysql implementation
* Consolidate entry php scripts
* Fix configuration/validation

Closes #8. Closes #7. Closes #5. Closes #4.

### CODE REVIEW

**Comment by kabel** [comment]
This should be a fun review. I'm almost certain I left a golden nugget for you to find.

**Comment by saltybeagle** [comment]
I think the golden nugget is in here: https://github.com/unl/GoURL/commit/9f3a21f1f822cdc0c4344be40784871131da1864

**Comment by kabel** [comment]
^ partial commit fail.

**Comment by mfairchild365** [comment]
I FOUND A NUGGET! I can create multiple records for a single URL.

**Comment by kabel** [comment]
I rechecked the production system and can confirm that _logged in_ users are able to get multiple records for a single URL. _Anonymous_ users will only get the single record. This logic remains the same here.

**Comment by mfairchild365** [comment]
One note. I think we should move away from using placeholders as labels. While the main input to shorten a URL does have a label, it is visually hidden, leaving only the placeholder to help the user. I think it should be visible.

**Pull request merged**
